#! /usr/bin/perl -w

my $lm = 0;

while (<>) {
	chomp;

	my ($k, $v) = split;

	if ($k !~ /;/) {
	  $k =~ tr#/#;#;
	} 
	printf "%-40s %s\n", $k, $v;

	$lm = length $k if length($k) > $lm;
}

#print "#LM : $lm\n";

