#! /usr/bin/perl -w

use strict;

my $date = `date`;
chomp $date;
my $year = `date "+%Y"`;
chomp $year;

foreach (@ARGV) {
  my $src = $_;

  next if (-d $src);
  mkdir $src;

  my $dst;

  $dst = "$src/$src.c";
  open OUT, ">$dst" || die "Can't open $dst file";
  print_header($src, $dst);
  print_header_c($src, $dst);
  close OUT;

  $dst = "$src/$src.h";
  open OUT, ">$dst" || die "Can't open $dst file";
  print_header($src, $dst);
  print_header_h($src, $dst);
  close OUT;
}



sub print_header
{
  print OUT <<EOT;
/*
 *
 * ze-filter - Mail Server Filter for sendmail
 *
 * Copyright (c) 2001-2017 - Jose-Marcio Martins da Cruz
 *
 *  Auteur       : Jose Marcio Martins da Cruz
 *                 jose.marcio.mc@gmail.com
 *
 *  Historique   :
 *  Creation     : $date
 *
 * This program is free software, but with restricted license :
 *
 * - ze-filter is distributed only to registered users
 * - ze-filter license is available only non-commercial applications,
 *   this means, you can use ze-filter if you make no profit with it.
 * - redistribution of ze-filter in any way : binary, source in any
 *   media, is forbidden
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * More details about ze-filter license can be found at ze-filter
 * web site : http://foss.jose-marcio.org
 */

EOT
}

sub print_header_c
{
  my ($src, $dst, undef) = @_;
  print OUT <<EOT;

#include <ze-sys.h>
#include <ze-filter.h>
#include <$src.h>


EOT
}

sub print_header_h
{
  my ($src, $dst, undef) = @_;

  my $tag = $dst;
  $tag =~ tr/a-z\-\./A-Z__/;

  print OUT <<EOT;

#ifndef $tag



# define $tag    1
#endif /* $tag */

EOT
}
