#!/usr/local/perl/bin/perl -w

use strict;


my @TMP;
my $nl = 0;
my $nok = 0;

my $t = 0;
my $s = "";
my $p = "";

my $new = 0;

foreach (<>) {
  chomp;

  s/KBYTES\(/KBYTES=\(/;

  $nl++;
  @TMP = split;

  next if $#TMP < 0;

  if ($TMP[0] =! /------/) {
    $new = 1;
    print $_, "\n";
    $t = $TMP[0];
    next;
  } else {
    print $s if $t != $TMP[0] && $new == 0;
    $new = 0;
  }

  shift @TMP;

  # print $s if $t != $TMP[0];

  # next if $t == $TMP[0];

  $s = sprintf ("%d CONN=(%d) ABRT=(%d) MSGS=(%d) RCPT=(%d) FILES=(%d)",
                $TMP[0],
                $TMP[1],
                $TMP[10],
                $TMP[2],
                $TMP[3],
                $TMP[5]);

  $s .=  sprintf(" XFILES=(%d) THROTTLE=(%d) RESFAIL=(%d) RESFORG(%d) \n",
                 $TMP[4],
                 $TMP[15],
                 $TMP[12],
                 $TMP[13]);

  $t = $TMP[0];

  #print $s;

  $nok++;
}

# print $s;

#printf "NL   %6d\n", $nl;
#printf "NOK  %6d\n", $nok;


__END__

