#! /bin/sh

#
# indiquez le chemin complet de l'executable rrdtool
# par defaut il est installe dans /usr/local/rrdtool/bin
#
RRDBIN=/opt/rrdtool/bin/rrdtool

RRDDIR=rrd
START="--start 900000000"

database="j-grey"

echo "RRDTool database : $database"


#                        dt     Dt
#       1    288   -     5 m    1 d
#      12    168   -     1 h    7 d
#      72    124   -     6 h   31 d
#     144    124   -    12 h   62 d
#    1152    365   -     4 d    4 y

test -f $RRDDIR/$database.rrd || $RRDBIN create $RRDDIR/$database.rrd \
                $START \
                --step 300 \
                DS:WAIT:GAUGE:600:U:U \
                DS:VALID:GAUGE:600:U:U \
                DS:WHITE:GAUGE:600:U:U \
                DS:BLACK:GAUGE:600:U:U \
                RRA:AVERAGE:0.99:1:576 \
                RRA:AVERAGE:0.99:12:168 \
                RRA:AVERAGE:0.99:72:124 \
                RRA:AVERAGE:0.99:144:124 \
                RRA:AVERAGE:0.99:1152:365

