#
# Makefile to convert text files into BerkeleyDB format
#
.DONE	: done

.SUFFIXES: .txt .db 

VPATH = /etc/ze-filter

#
# Databases to create
#
OBJ     = ze-urlbl.db ze-policy.db ze-rcpt.db ze-bayes.db
JBINDIR = /usr/bin

#
# POLICY_SRC variable defines which files to include in your
#      policy database
#
# Depending on your Operating System, you can use one of this options :
# - GNU make
POLICYSRC = $(wildcard ze-policy.*.txt)
# - SunOS make
#POLICYSRC:sh =ls ze-policy.*.txt
# - List text files by hand
#POLICYSRC = ze-policy.grey.txt ze-policy.badmx.txt ze-policy.base.txt

POLICYSRC = $(wildcard ze-policy.??-*.txt ze-policy.??-*.txt | sort)
POLICYDEF = $(wildcard ze-policy.z-*.txt | sort)

.txt.db :
	@echo "** Building $@ ..."
	@if [ -f $@ ] ; then \
		mv $@ $@.old ; \
	fi
	$(JBINDIR)/ze-makemap -b $@ -m e -m s < $<

all : $(OBJ) done

ze-policy.txt : $(POLICYSRC) $(POLICYDEF)
	cat  $(POLICYSRC) $(POLICYDEF) > $@

ze-rcpt.db : ze-rcpt.txt
	@if [ -f ze-rcpt.db ] ; then \
		mv ze-rcpt.db ze-rcpt.db.old ; \
	fi
	$(JBINDIR)/ze-makemap -b $@ -m e -m u < $<

clean	:
	rm -f *.db 

done :
	@echo "*** Telling ze-filter to reload databases..."
	$(JBINDIR)/ze-ndc reload databases
	$(JBINDIR)/ze-ndc reload lrdata
	@rm -f *.db.old

