#! /usr/bin/perl -w

use strict;

my $cfdir = "/etc/ze-filter";

my @FILES = qw(ze-regex ze-oradata ze-access);

my %TAGS = ('ze-regex' => 'REGEX',
	    'ze-oradata' => 'ORACLE-DATA',
	    'ze-access' => 'ACCESS');

my %LABEL = ('ze-regex' => 'Pattern matching',
	     'ze-oradata' => 'Oracle definitions',
	     'ze-access' => 'Access table');

foreach my $file (@FILES) {
  my $fin = "$cfdir/$file";

  next unless -f $fin;

  open FIN, "<$fin" || die "$@";
  print <<TXT;
# *******************************************************
#
# $LABEL{$file}
#
# *******************************************************
<$TAGS{$file}>

TXT

  print $_ while (<FIN>);

  print <<TXT;

</$TAGS{$file}>

TXT

}
