#! /usr/bin/perl -w

use strict;

my $date = `date`;
chomp $date;

foreach (@ARGV) {
  my $src = $_;

  my ($dst, $tag);

  $dst = "$src.c";
  $tag = sprintf "__%s_H", uc $src;
  open OUT, ">$dst" || die "Can't open $dst file";
  print_copyright($src, $dst);
  print_header_c($src, $dst);
  close OUT;

  $dst = "$src.h";
  open OUT, ">$dst" || die "Can't open $dst file";
  print_copyright($src, $dst);
  print_header_h($src, $dst, $tag);
  close OUT;
}



sub print_copyright
{
  my ($src, $dst) = @_;
  my $year = `date +"%Y"`;
  chomp $year;

  print OUT <<EOT;
/*
 *
 * ze-filter - Mail Server Filter for sendmail
 *
 * Copyright (c) 2001-2018 - Jose-Marcio Martins da Cruz
 *
 *  Auteur       : Jose Marcio Martins da Cruz
 *                 jose.marcio.mc\@gmail.com
 *
 *  Historique   :
 *  Creation     : $date
 *
 * This program is free software - GPL v2., 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

EOT
}

sub print_header_c
{
  my ($src, $dst, undef) = @_;
  print OUT <<EOT;

#include <ze-sys.h>
#include <ze-filter.h>
#include <$src.h>

/* ****************************************************************************
 *                                                                            *
 *                                                                            *
 **************************************************************************** */

EOT
}

sub print_header_h
{
  my ($src, $dst, $tag, undef) = @_;

  $tag =~ tr/a-z\-\./A-Z__/;

  print OUT <<EOT;

#ifndef $tag
/**
 * \@addtogroup Defaulf
 *
 * \@{
 */

/** \@} */

# define $tag    1
#endif /* $tag */

EOT
}

