#! /bin/bash

PATH=/usr/bin:$PATH

DATE=`date +%y%m%d`
echo $DATE > aux/timestamp

HERE=`pwd`
VERSION=`basename $HERE`
VERSION=`echo $VERSION | sed s/zefilter-// | sed s/ze-filter-//`
echo $VERSION > aux/release

dev-tools/set-release

#set -x

autoheader
aclocal -I m4
libtoolize -i -c --no-warnings -q --recursive --automake
#libtoolize -c -f --automake
automake --add-missing -c
autoconf 

/bin/rm -rf $(find . -name autom4te.cache)
