#! /bin/bash

PATH=/usr/bin:$PATH

DATE=`date +%y%m%d`
echo $DATE > aux/timestamp

HERE=`pwd`
VERSION=`basename $HERE`
VERSION=`echo $VERSION | sed s/zefilter-// | sed s/ze-filter-//`
echo $VERSION > aux/release

dev-tools/set-release

set -x

autoreconf

