#! /usr/bin/perl -w

use strict;

exit 1 if $#ARGV < 0;

my $look = pop @ARGV;
$look = uc($look);

while (<>) {
  chomp;

  next if /^\s*#/;
  next if /^\s*$/;

  my ($k, $v) = split("=", $_, 2);
  next unless defined $k and defined $v;

  trim_spaces($k);
  trim_spaces($v);

  $k = uc($k);
  if ($k eq $look) {
    print $v, "\n";
    exit 0;
  }
}

exit 0;

sub trim_spaces {
  $_[0] =~ s/^\s+|\s+$//g;
}

