#! /bin/sh

DATE=`date +%y%m%d`
echo $DATE > aux/timestamp

HERE=`pwd`
VERSION=`basename $HERE`
VERSION=`echo $VERSION | sed s/zefilter-// | sed s/ze-filter-//`

BRANCH=$(git branch -l | grep '*' | awk '{print $2}')

echo $BRANCH-$DATE > aux/version

