#! /bin/bash

[ -n "$DIRS" ] || DIRS="
  libs :wqlibjoe src ze-scanfile ze-printstats ze-makemap
  ze-logserver ze-greyd ze-bayes-tbx scratch zechklib zelib
"

for dir in $DIRS
do
  echo "* DIR = $dir"
  FUNCS=$(awk '{print $1}' zelib/funcs2cvt.txt)
  for func in $FUNCS
  do
    nfunc=$(grep ^$func zelib/funcs2cvt.txt | awk '{print $2}')
    FILES=$(grep -l -d skip $func $dir/*.c $dir/*.h 2>/dev/null)
    for file in $FILES
    do
      printf "  %-32s %-20s %s\n" $file $func $nfunc
      sed -i -e "s/$func/$nfunc/g" $file
    done
  done
done


