
static xfilesdef_T xfilesdef[] =
{
  { "ade", "Microsoft Access project extension", "MS-UNSAFE"},
  { "adp", "Microsoft Access project", "MS-UNSAFE"},
  { "app", "Visual FoxPro Application", "OFFICE2000"},
  { "bas", "Microsoft Visual Basic class module", "MS-UNSAFE"},
  { "bat", "Batch file", "MS-UNSAFE"},
  { "bin", "Binary File", "LOCAL"},
  { "btm", "4DOS Batch To Memory Batch File", "LOCAL"},
  { "chm", "Compiled HTML Help file", "MS-UNSAFE"},
  { "cmd", "Microsoft Windows NT Command script", "MS-UNSAFE"},
  { "com", "Microsoft MS-DOS program", "MS-UNSAFE"},
  { "cpl", "Control Panel extension", "MS-UNSAFE"},
  { "csh", "Unix shell extension", "OFFICE2000"},
  { "dll", "Dynamic Link Library", "LOCAL"},
  { "drv", "Device Driver", "LOCAL"},
  { "exe", "Program", "MS-UNSAFE"},
  { "fxp", "Visual FoxPro Compiled Program", "OFFICE2000"},
  { "hlp", "Help file", "MS-UNSAFE"},
  { "hta", "HTML program", "MS-UNSAFE"},
  { "inf", "Setup Information", "MS-UNSAFE"},
  { "ini", "Initialization/Configuration File", "LOCAL"},
  { "ins", "Internet Naming Service", "MS-UNSAFE"},
  { "isp", "Internet Communication settings", "MS-UNSAFE"},
  { "js", "JScript file", "MS-UNSAFE"},
  { "jse", "File Encoded Javascript", "LOCAL"},
  { "ksh", "Unix shell extension", "OFFICE2000"},
  { "lnk", "Shortcut", "MS-UNSAFE"},
  { "mdb", "Microsoft Access program", "MS-UNSAFE"},
  { "mde", "Microsoft Access MDE database", "MS-UNSAFE"},
  { "mdt", "Microsoft Access Workgroup Information", "OFFICE2000"},
  { "mdw", "Microsoft Access Workgroup Information", "OFFICE2000"},
  { "msc", "Microsoft Common Console document", "MS-UNSAFE"},
  { "msi", "Microsoft Windows Installer package", "MS-UNSAFE"},
  { "msp", "Microsoft Windows Installer patch", "MS-UNSAFE"},
  { "mst", "Microsoft Visual Test source files", "MS-UNSAFE"},
  { "ops", "Office XP settings", "OFFICE2000"},
  { "pcd", "Photo CD image, Microsoft Visual compiled script", "MS-UNSAFE"},
  { "pif", "Shortcut to MS-DOS program", "MS-UNSAFE"},
  { "prg", "Visual FoxPro Program", "OFFICE2000"},
  { "reg", "Registration entries", "MS-UNSAFE"},
  { "scr", "Screen saver", "MS-UNSAFE"},
  { "sct", "Windows Script Component", "MS-UNSAFE"},
  { "shb", "Shell Scrap object", "MS-UNSAFE"},
  { "shs", "Shell Scrap object", "MS-UNSAFE"},
  { "sys", "System Device Driver", "LOCAL"},
  { "url", "Internet shortcut", "MS-UNSAFE"},
  { "vb", "VBScript file", "MS-UNSAFE"},
  { "vbe", "VBScript Encoded script file", "MS-UNSAFE"},
  { "vbs", "VBScript file", "MS-UNSAFE"},
  { "vxd", "Virtual Device Driver", "LOCAL"},
  { "wsc", "Windows Script Component", "MS-UNSAFE"},
  { "wsf", "Windows Script file", "MS-UNSAFE"},
  { "wsh", "Windows Script Host Settings file", "MS-UNSAFE"},
  { "xmf", "Windows Metafile", "LOCAL"},
  {NULL, NULL, NULL}
};

