.TH j-printstats 1 "25 May 2002" "ze-filter 1.1"
.SH NAME
Joe's ze-filter \- A milter based filtering mail daemon for sendmail
.SH SYNOPSIS
.B j-printstats

.SH DESCRIPTION
.I  j-printstats
displays the contents of ze-filter internal activity counters.


.SH "SEE ALSO"
ze-filter(8), j-scanfile(1), ze-filter.cf(5)

.SH BUGS
.I Bugs ???
Did you say 
.I bugs ???
Where did you see a
.I bug ???
.PP
If you find yourself in a very improbable situation of finding a bug,
please send me a bug repport.

.SH AUTHOR
Joe's ze-filter was written by Jose Marcio Martins da Cruz : 
martins@paris.ensmp.fr
.PP

